### ISSUE TITLE
midres: buggy audio 

### ISSUE THREAD

**Issue by Harmonica9000** [jotego/jtcores#198]
Periodically the audio will distort. I've got a few recordings of it happening.

Example 1: https://youtu.be/fkYGO-PYITE

Example 2: https://youtu.be/mg0PZZ5zRPI

I also noticed that a scrolling effect isn't working properly. The rocky background is supposed to slide left or right to expose something like a factory but it's either happening in strips or not at all.

https://youtu.be/ZVXEnkyee3g

These were recorded on the JP version.

**Comment by jotego** [comment]
- verilator simulation of the [vgm](https://vgmrips.net/packs/pack/midnight-resistance-arcade#01-surging-power-bgm-1) sounds correct.

**Comment by jotego** [comment]
Fixed in 4fa33c9a

The Hu CPU has its own cen signal generated internally that will produce
6.89 MHz for a 48 MHz clock. 

Gating the Hu clock by 3, getting closer to 2Mhz, fixes the music problems in midres. The reason probably is that cpu_din is not ready in time with the ungated clock. The Hu CPU seems to execute functions at different clock cycles in between the internal cen signal so it may be getting the data before its ready unless the clock is gated.
