### ISSUE TITLE
change core name?

### ISSUE THREAD

**Issue by gregmariotti** [jotego/jtcores#247]
know you renamed them for copyright reasons, but is there any easy way for me to change the .json files naming and not break the games? (i.e jtcontra to Contra, etc.) thanks

**Comment by jotego** [comment]
Please check out analogue's documentation about the JSON files. 

They made things quite convoluted so I don't dare say in how many places you'll have to change the name. 

Another aspect is that a single core may support many games so you'll find it hard anyway. 

Ideally, Analogue would make the search system work using game titles instead of core names. That would solve the issue for everyone.
