### ISSUE TITLE
simson: scene 17

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#329]
Curtains are big sprites that should cover other sprites underneath,
particularly the white fusuma (Japanese slide doors) should not be visible

The full sprite LUT is not parsed within the line interval. If the writting
overruns the line buffer switch, the fusuma is written on the next line and
will not be overwritten because old sprites take priority in this game

It is hard to make the logic go faster because the pixel draw process requires
two clock cycles, precisely because of the old-sprite priority setting

Fixed in 8568b5c9

**Comment by asturur** [comment]
Hi!
Not sure what scene17 is, but yesterday i played all the game and after the boss battle on the japanese stage ( the tv studio one ) i got some glitches on screen while moving forward to the 2 final boss battles.

I never see how the real hardware behave there since i never got that far.
I was playing bart in the 2 player version of the game.

**Comment by jotego** [comment]
This is fixed but I have not released the new file yet.

**Comment by asturur** [comment]
So scene 17 is this particular one?

**Comment by jotego** [comment]
This is scene 17

![frame_00002](https://github.com/jotego/jtcores/assets/1863036/f4bf4f2e-5536-4993-8420-b4f309588c27)

It looks like it still happens a bit during gameplay, allegedly improved. The scene simulation is fine but that has less SDRAM overhead than the actual core.

**Comment by jotego** [comment]
I have been able to speed up the sprite logic a bit, I can see that it has more margin in simulation. 

I have updated the files in JTBIN. Please let me know if it still occurs.
