### ISSUE TITLE
cps1 final fight have no "Allow Continue" dipswitch

### ISSUE THREAD

**Issue by hgage2003** [jotego/jtcores#452]
Game can be played, but no continues allowed.
You need to add this to /Presets/Interact/Final Fight(World, set 1).json :
{
  "name": "Allow Continue",
  "id": 14,
  "type": "check",
  "enabled": true,
  "persist": true,
  "address": "0xfa000000",
  "defaultval": 1,
  "value": 0,
  "value_off": 4194304,
  "mask": "0xFFBFFFFF"
},

**Comment by jotego** [comment]
Thanks for pointing at this. The problem is that the Pocket firmware cuts the number of options and behaves in an unstable way when the option list is too long.
I have requested Analogue to support more options in the _Core Settings_, but it will likely take them months to implement it.
Another solution is to list options to drop per game in my configuration files for each core. But that would be a manual task to do on over 200 games (close to 1000 if you count the alternate games). I do not have the bandwidth to do that. So I'd rather wait for Analogue. Sorry about that.
