### ISSUE TITLE
bubl: question about EXTEND

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#478]
The EXTEND letters are supposed to appear in a certain order according to [Nicola Salmoria](https://mamelife.blogspot.com/2006/08/completed-at-last.html):

- Either ETN or XED

lord_dOt reported via Discord that he has seen out of sequence letters. I have not been able to reproduce the problem in v1.5.5. Apparently you have to wait for the demo loop twice and then it will happen. [Video](https://www.youtube.com/watch?v=Lp_T1Q7Jjdk)

_Note:_ the number of letter bubbles depend on how many enemies you killed at once in the previous stage.

**Comment by lorddOt7** [comment]
The issue is easily replicated by waiting 2 complete loop of the attrac mode (after a cold boot of the mister) and by starting a game the third time the bubble bobble logo appear on the screen. On the third or fourth level the letter appear not based on the two block ETN or XED. 
![IMG_7594](https://github.com/jotego/jtcores/assets/155982684/6a08fdee-ce9f-426a-bb26-c200b74715f9)
![IMG_7593](https://github.com/jotego/jtcores/assets/155982684/d5415e51-43f2-40bc-8103-094d0e81f0ac)

**Comment by lorddOt7** [comment]
Tried custom version 03c92221 with no luck. The bug remains.

**Comment by jotego** [comment]
Thank you for taking the time to look into this. I will close the issue then.
