### ISSUE TITLE
Cps1 and cps2 control change pocket

### ISSUE THREAD

**Issue by SeanerGame** [jotego/jtcores#569]
I have noticed I can no longer change the control setup on the pocket for any of the cps1 and cps2 fighting games.

**Comment by jtmiki** [comment]
I tried the following CPS1 and CPS2 fighting games on the Pocket and I was able to change the control settings for all games.

CPS1
-Final fight
-Street fighter II World Warrior
-Street fighter Zero

CPS2
-Darkstalkers the night warriors
-Marvel super heroes
-X-men children of the Atom

You would better to delete configuration file because you have some old files.
