### ISSUE TITLE
Arcade Cabinet 4-Player Assignment Feature/Enhancement

### ISSUE THREAD

**Issue by Serkeliss** [jotego/jtcores#640]
With the release of the TMNT core to the public, I was hoping that there would be a way to create a method to reassign player placement within the core, similar to how the Gauntlet 1 core does this.

A lot of these 4-player games, like Gauntlet, Simpsons, TMNT, etc, have a specific placement for characters to players.  An example would be in TMNT where they have Players laid out like Leonardo, Michelangelo, Donatello, Raphael as Player1, Player2, Player3, Player4.  Some 4-player arcade cabinets (usually the modern, custom variety) are built so that the player assignment is actually aligned like the following: P3, P1, P2, P4.  This is to ensure that most 1-2 player games would have the focus in the middle of the cabinet and not off to the left.

Not all cabinets suffer from this.  Like when a cabinet just allows you to select your character on start/death and didn't have a 1:1 pairing to the character, but for the ones that did it would be super helpful.  I think Gauntlet 1 was the only game that I found that had this type of switch or DIP control that allowed you to force an assignment to a particular controller layout, but I could see when a lot of the games that had the characters assigned by player number/placement would be fantastic and incredibly useful.

**Comment by jotego** [comment]
This is already support both for TMNT and Simpsons by the two-player alternative versions. It is just that the main one is the four-player version. I know it is a bit of an inconvenience but I prefer to keep the same game organization as MAME and they have the 4-player one as the main title.

I could add a message in the credits screen or the README file to remind people of the existence of the other versions.

Having to teach users to re-configure their input assignment is about the same effort if not more than telling them about the existence of the other game versions. I do not see questions going away because of this change.

Thank you for your kind suggestion.
