### ISSUE TITLE
toki: author field is incorrect on Pocket

### ISSUE THREAD

**Issue by davewongillies** [jotego/jtcores#651]
The [core.json for the Toki](https://github.com/jotego/jtbin/blob/master/pocket/raw/Cores/jotego.jttoki/core.json#L11) core is set to `solal jacob`. Unfortunately this stops the core from working. It works if the `author` field is set to `jotego`

**Comment by jotego** [comment]
Fixed in ba5450ab546c631a5e48fce0ea1f432fa5de7c02
I do not see a good solution for the author field as it is what the Pocket uses for indexing the files. Most people let the updater sort out the files anyway...
It looks like the core on-screen credits were not enabled. By enabling them, the author information is shown and Solal's name is clear.
