### ISSUE TITLE
s18: mwalk brightness too high

### ISSUE THREAD

**Issue by SumolX** [jotego/jtcores#734]
Almost all cores have similar levels except for moonwalker.  The brightness needs to be turned down on my arcade crt cabinet by a significant amount.  Alien Syndrome looks perfect for reference.

![IMG_5960](https://github.com/user-attachments/assets/fa099971-5253-4e72-8407-ad5d4a7c26d1)

**Comment by jotego** [comment]
How about the other s18 titles?

**Comment by SumolX** [comment]
Just tested all s18 titles and they all exhibit this issue.

**Comment by jotego** [comment]
This is the core output captured in simulation. The brightness is correct:

![frame_01438](https://github.com/user-attachments/assets/b28c964c-40b7-4ea6-8062-f0e13362cdf8)

What happens in your screen is that the reference level is not being captured correctly. This is likely due to the peculiar video timing of this system. This causes synchronization problems to several users (see #692). In your case, your TV set can synchronize but with incorrect brightness and probably incorrect colors too.

So far, there is no solution for this from the core side. We may work on a tweak (#729) that will likely fix this for you at the cost of slightly different gameplay/music speed.
