### ISSUE TITLE
riders/simson: missing lines in objects

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#741]
Objects may miss lines under some circumstances. It can be seen in the score of _Parodius da!_ and at the end of the second stage of _Sunset Riders_.

Enemies at the top are missing lines
![20240727_090653-screen](https://github.com/user-attachments/assets/84bff205-67d2-4297-94e8-b4977643a2ce)

`CREDIT` characters are missing lines
![20240728_062813-screen](https://github.com/user-attachments/assets/1ea0bc1e-83d9-4632-8caf-bb241b31416f)

**Comment by jotego** [comment]
simulation scenes 6 and 7 in ssriders present this issue.

**Comment by rp-jt** [comment]
The issue in Sunset Riders seems to be that the module painting the objects does not have enough time to finish drawing the sprites before changing the line. 
In the case of the presented scene, it appears that some more objects are drawn even being not visible, as it can be seen in this scene with only sprites:

![7obj](https://github.com/user-attachments/assets/f5262ff2-976a-46b1-82a8-8f254d0c0901)

Accelerating the process seems to solve the issue in Sunset Riders.

Right now, jtriders uses the jtsimson_obj. I am going to make an independent module for riders simplifying this (jtriders_obj) in order to solve this issue.

For Parodius, it appears that the characters presenting the issue are not in the objects layer, so a similar approach has not been useful in this case.

**Comment by rp-jt** [comment]
@gyurco 
The new module for the objects will be considering only the chips 053245/053244, so it won't be compatible with Xmen anymore. Xmen will be separated to another core

**Comment by gyurco** [comment]
> @gyurco The new module for the objects will be considering only the chips 053245/053244, so it won't be compatible with Xmen anymore. Xmen will be separated to another core

OK. For #759, probably it'll be even better.

**Comment by jotego** [comment]
We started out with a unified module supporting the two chipsets 05324x but the code is becoming too messy. So @rp-jt will split it into two modules. One for 053244/5 and another for 053246/7. This means that Parodius support may be taken out from JTSIMSON to its own core too.

**Comment by rp-jt** [comment]
Missing lines solved for ssriders in 17e9b0d28c59b28a3b2ebd7da9dc5ad6e0967dcb

Problem in Parodius not related to objects. Creating a separate issue for this
