### ISSUE TITLE
JT Cores Analogizer  SNAC support: only detected 2 action buttons with PCEngine 6 btn controller (Avenue Pad)

### ISSUE THREAD

**Issue by RndMnkIII** [jotego/jtcores#753]
Testing several SNAC game controllers with JT Cores that uses 3 o more action buttons I've noticed that when configure SNAC to work with PCEngine game controller and when I'm using the Avenue Pad 6 action button game controller configured into  B mode (6 btn mode) only works the first two action buttons (I, II), the remaining action buttons (III to VI) seems to be ignored. Tested with several games: Golden Axe, Shadow Dancer, Street Fighter II, Street Fighter Alpha 3). 
https://drive.google.com/file/d/1EU2KFYHv8E5ER3Dy0BVRwuQrnMLGu47r/view?usp=sharing

**Comment by rp-jt** [comment]
Even though the module managing all SNAC controllers leads both options to the same point, the module managing the PCE 2/6 btn controllers differentiated depending on the controller type value.

We had used the value for PCE 2 BTN (0x04) as default, but this deactivated the extra buttons in PCE 6 BTN.

I changed the configuration file to default now to PCE 6 BTN (0x05), which works for both controllers.

Fixed in 62fcc49ab844c2f92bb38500db3295cf73fe6060
