### ISSUE TITLE
riders: xmen. plane duplicated and misplaced for very large shrink values

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#762]
In the intro sequence, the Blackbird (X-men's plane) should appear from the distance. The zoom does not work well as it displays it duplicated for large reduction and it seems to offset it to the left and up/down. Eventually one of the two copies disappears because it seems to fall outside the screen. When the zoom shrinkage is not that aggressive, the ship appears correctly.

two planes
![20240810_093652-screen](https://github.com/user-attachments/assets/dc65c5e1-d6e1-4e82-9ae5-558824bb03d8)

two planes, bottom one visible
![20240810_093700-screen](https://github.com/user-attachments/assets/daad9661-18e2-454b-bc34-b4c009d0b9e9)

two planes (?), top one visible, a bit misplaced
![20240810_093705-screen](https://github.com/user-attachments/assets/56de6807-41a2-4739-9ae5-798b611396c4)

For this shrink level, the position seems correct
![20240810_093712-screen](https://github.com/user-attachments/assets/9433b65d-72af-426d-bbb3-56ba5cbcaf61)

**Comment by rp-jt** [comment]
In jt053246, vzoom/hzoom is obtained with 10 bits, but only 8 of them are considered to take the offset value from the zoffset array. In this case, vzoom/hzoom[9:8] was active, but the offset value taken was from the middle of the array, instead of an offset for large numbers of vzoom/hzoom (reduction). Something similar to what happened in #548. It can be solved in the same way

Examples in scenes 2 and 6

**Comment by rp-jt** [comment]
The duplication is produced by a large value of yz_add that doesn't trigger the condition if( yz_add[16] ) inzone = 0
Can be fixed by using |yz_add[17:16] and considering larger numbers

Scene 5
![5](https://github.com/user-attachments/assets/3599e83e-de9e-4382-8b96-596f5b0c3aeb)
